title: Jsh
description: My Personal Blog
author: jin su hyeon
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/jinsoohyun/
about: Student

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: jinshs-blog
google_analytics: ""

share:
  twitter_username: \#
  fb_appid: jsh05042


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
